security:
    encoders:
        App\Entity\User: bcrypt
    providers:
        database_users:
            entity: { class: App\Entity\User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/
            form_login:
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: micro_post_index
#                always_use_default_target_path: false
#                use_referer: true
#                failure_path:
            logout:
                path: security_logout
                target: micro_post_index
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
#         - { path/ ^/micro-post, roles: ROLE_USER }
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
