version: '3.1'

services:

  php:
    image: maciejslawik/php-fpm-xdebug:latest
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST_IP} idekey=${XDEBUG_IDE_KEY}"
      PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG_SERVERNAME}"
      COLUMNS: ${TERMINAL_COLS}
      LINES: ${TERMINAL_LINES}

  nginx:
    image: maciejslawik/nginx:latest
    ports:
      - ${NGINX_PORT}:80
    links:
      - php
    environment:
      COLUMNS: ${TERMINAL_COLS}
      LINES: ${TERMINAL_LINES}
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/sites-available/vhost.conf
      - .:/var/www/html

  db:
    image: mysql:8.0
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      COLUMNS: ${TERMINAL_COLS}
      LINES: ${TERMINAL_LINES}
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
