parameters:
  locale: 'en'
  mail_from: '%env(MAILER_FROM)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Twig\AppExtension:
    arguments:
      $locale: '%locale%'

  App\Mailer\Mailer:
    arguments:
      $mailFrom: '%mail_from%'

  App\EventListener\LikeNotificationSubscriber:
    tags:
      - { name: doctrine.event_listener, event: onFlush, connection: default }
